name: Deploy Flask App

on:
  push:
    branches: [ "main" ]  # deploy only after merge

permissions:
  contents: read
  packages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u shubhambhawsar-gvw --password-stdin

      - name: Build and push Docker image
        run: |
          IMAGE_NAME=ghcr.io/shubhambhawsar-gvw/patientsafe_app:latest
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            IMAGE_NAME=ghcr.io/shubhambhawsar-gvw/patientsafe_app:latest
            docker pull $IMAGE_NAME
            docker stop patientsafe_app || true
            docker rm patientsafe_app || true
            docker run -d --restart=always -p 5700:5700 --name patientsafe_app $IMAGE_NAME
