name: Deploy Flask App

on:
  push:
    branches: [ "main" ]  # deploy only after approved merge to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t patientsafe_app .

      - name: Save image as tar
        run: docker save patientsafe_app -o patientsafe_app.tar

      - name: Copy image to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          source: "patientsafe_app.tar"
          target: "~/"

      - name: Deploy on server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASS }}
          script: |
            docker load -i ~/patientsafe_app.tar
            docker stop patientsafe_app || true
            docker rm patientsafe_app || true
            docker run -d -p 5700:5700 --name patientsafe_app patientsafe_app
